name: PlatformIO CI Pipeline

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - develop

jobs:
  build-and-test:
    name: Build and Test with PlatformIO
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install PlatformIO and clang-format
        run: |
          sudo apt-get update
          sudo apt-get install -y clang-format
          pip install -U platformio

      - name: Check C++ code format with clang-format
        run: |
          find src/ test/ -name '*.cpp' -o -name '*.h' \
            | xargs clang-format -style=file -n --Werror

      - name: Run PlatformIO tests on native environment
        run: |
          pio test -e native
